server:
  port: 8002

spring:
  application:
    name: cloud-pay-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver      #mysql驱动包
    url: jdbc:mysql://localhost:3306/shoppgo?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: sa123
#eureka:
#  client:
#    #表示是否将自己注册进EurekaServer默认为true
#    register-with-eureka: true
#    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:7001/eureka
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.windAndCloud.test.entity       #所有Entity别名类所在包